### ISSUE TITLE
Sockets time out and cause mutex to be locked forever

### ISSUE THREAD

**Issue by tylerjw** [rexroni/blackjay#1]
On the client if a socket times out the synchronize function exits without freeing the mutex and we are in a bad state.  Here is the console output:

```
send_file: file size: 3859313
2017-02-28 18:43:32,683| ERROR   | Socket exception: Operation timed out (60)
2017-02-28 18:43:32,684| ERROR   | Could not establish connection from ('127.0.0.1', 51345) to remote side of the tunnel
Traceback (most recent call last):
  File "client.py", line 244, in <module>
    main()
  File "client.py", line 234, in main
    synchronize(force_pull=True)
  File "client.py", line 146, in synchronize
    send_file(os.path.join('.blackjay','c2s.zip'), sock)
  File "/Users/tylerjw/workspace/python/blackjay/networking.py", line 33, in send_file
    send_size(data, sock)
  File "/Users/tylerjw/workspace/python/blackjay/networking.py", line 69, in send_size
    data_sent = sock.send(send_data[total_sent:])
BrokenPipeError: [Errno 32] Broken pipe
syncing due to ./.DS_Store
quitting due to locked mutex
```

**Comment by rexroni** [comment]
Mibad.  I had most of the syncrhonize wrapped in a "try: ... except: mutex.release()" statement, because for a release version it makes sense to always unlock the mutex.  I had to comment out the "try/except" parts to debug something else, and I forgot to decomment them.
