### ISSUE TITLE
Client failing to connect to server and throwing exception

### ISSUE THREAD

**Issue by tylerjw** [rexroni/blackjay#3]
I'm now having trouble even getting the client to communicate with the server.  Here is the output:

```
$ python client.py ~/blackjay
Looking for blackjay in /Users/tylerjw/blackjay
starting ssh tunnel
{('0.0.0.0', 55970): True}
Client running... watching for changes
any updates? True
<socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
Trying to connect on : ('127.0.0.1', 55970)
<socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 55971), raddr=('127.0.0.1', 55970)>
Traceback (most recent call last):
  File "client.py", line 244, in <module>
    main()
  File "client.py", line 234, in main
    synchronize(force_pull=True)
  File "client.py", line 135, in synchronize
    remote_meta = json.loads(recv_all(sock).decode('utf8'))
  File "/Users/tylerjw/.pyenv/versions/3.4.6/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/Users/tylerjw/.pyenv/versions/3.4.6/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/tylerjw/.pyenv/versions/3.4.6/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
syncing due to ./weaveringrally_blog/temp
quitting due to locked mutex
```

On the server side there is no output.

**Comment by tylerjw** [comment]
I printed the data that I'm getting back from the server and it is this:

`data received: you fucked up`

**Comment by tylerjw** [comment]
If I print the data on the server side just before it sends back the above message I get:

`data received: b'gimme the metadata'`

**Comment by tylerjw** [comment]
This was a result of using different revisions of the code.  Disregard.
